# Generated by Django 4.2.4 on 2023-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField()),
                ('date_created', models.DateField()),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField()),
                ('post_id', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('image', models.CharField()),
                ('age', models.IntegerField()),
                ('animal_type', models.CharField()),
                ('breed', models.CharField()),
                ('description', models.CharField()),
                ('gender', models.CharField()),
                ('owner_id', models.IntegerField()),
            ],
        ),
    ]
